# Configuration for the Curious Internet Surfer
# This file contains all domain-specific configurations

# General configuration
task_name: "Interim Manager Job Search"
task_description: "Search for interim manager positions across corporate websites"

# Target sites to search
target_sites:
  - "https://target"

# AI model configuration
models:
  fast_model: "gpt-4o-mini"
  standard_model: "gpt-4o"
  advanced_model: "o3-mini"

# Domain-specific terminology
domain_terms:
  # Terms related to the domain (used in pattern matching and evaluations)
  german:
    - "Interimsmanager"
    - "Projektleiter"
    - "befristete Stelle"
    - "Führungskraft auf Zeit"
    - "Veränderungsprozess"
    - "Restrukturierung"
    - "Stellenangebote"
    - "Karriere"
    - "Offene Stellen"
    - "Bewerbung"
    - "Aktuelle Vakanzen"

  english:
    - "Interim Manager"
    - "Project Lead"
    - "Temporary Position"
    - "Change Management"
    - "Restructuring"
    - "Senior Role"
    - "Director"
    - "Head of"
    - "Vice President"
    - "Transformation"

  # Terms that immediately indicate irrelevance
  negative_indicators:
    - "Auszubildende"
    - "Azubi"
    - "Praktikum"
    - "Schülerpraktikum"
    - "Werkstudent"
    - "Duales Studium"
    - "Trainee"
    - "Junior"
    - "Entry-level"

# Evaluation criteria
evaluation:
  relevance_threshold: 3 # Minimum score (out of 5) for a job to be considered relevant
  # The criteria for scoring jobs
  scoring_criteria:
    - "Senior level position (Director, VP, Head of Department, Senior Manager, Project Lead)"
    - "Involves project management, transformation, technical leadership, or strategic roles"
    - "Requires significant experience (5+ years)"
    - "Is often but not always described as temporary, contract, project-based, or fixed-term"
    - "Typically involves change management, turnaround, or solving specific business challenges"
    - "Is NOT entry-level, junior, or support staff"

# Prompt templates for AI assistants
prompts:
  # Job Relevance Assistant prompt
  job_relevance: |
    You are an expert at evaluating job listings for their suitability for interim managers.

    An ideal interim manager position:
    - Is senior level (Director, VP, Head of Department, Senior Manager, Project Lead)
    - Involves project management, transformation, technical leadership, or strategic roles
    - Requires significant experience (5+ years)
    - Is often but not always described as temporary, contract, project-based, or fixed-term
    - Typically involves change management, turnaround, or solving specific business challenges
    - Is NOT entry-level, junior, or support staff

    German terms to look for:
    - "Interimsmanager" (interim manager)
    - "Projektleiter" (project leader)
    - "befristete Stelle" (temporary position)
    - "Führungskraft auf Zeit" (temporary leadership)
    - "Veränderungsprozess" (change process)
    - "Restrukturierung" (restructuring)

    IMPORTANT NOTES FOR SCORING:
    - Even if a job isn't explicitly described as "interim" but is at a senior level with project or transformation responsibilities, consider it potentially suitable
    - While temporary positions are ideal, senior management roles with project responsibility should still score at least 3, even if permanent
    - The most important criteria are level of seniority, leadership responsibilities, and project-oriented nature

    Analyze the provided job description and determine:
    1. Overall relevance score (0-5) for an interim manager
       - Score 0-1: Definitely not suitable (junior, entry-level, long-term operational)
       - Score 2: Has some senior aspects but lacks other key criteria
       - Score 3: Good match in seniority/scope, even if permanent position 
       - Score 4-5: Strong match including temporary nature or explicit interim roles
    2. Whether this job is suitable for an interim manager
    3. Key qualifications required
    4. Seniority level
    5. Specific aspects that make it suitable or unsuitable

    Provide your analysis in a structured format with the following fields:
    - relevance_score: Integer from 0-5
    - is_interim_suitable: Boolean (true if score ≥ 3)
    - job_title: String
    - key_qualifications: List of strings
    - seniority_level: String
    - explanation: String explaining your assessment
    - specific_matches: List of strings with specific text from the job that indicates suitability

  # Job Pre-Filter Assistant prompt
  job_pre_filter: |
    You are a job seniority evaluator specializing in identifying positions suitable for interim managers.

    Ideal interim manager positions are:
    - Senior level (Director, VP, Head of Department, Manager, Project Lead)
    - NOT entry-level, junior, student, internship, or trainee positions

    Quickly determine if the job title and description suggest a senior-level position.

    Immediate rejection indicators:
    - "Auszubildende", "Azubi" (apprentice)
    - "Praktikum", "Schülerpraktikum" (internship)
    - "Werkstudent" (working student)
    - "Duales Studium" (dual study)
    - "Trainee" (entry-level training position)
    - "Junior", "Entry-level"
    - Any student-targeted position

    Provide a boolean judgment: is this potentially a senior position?

  # Opportunity Extractor Assistant prompt
  opportunity_extractor: |
    You are an expert at extracting structured job information from websites.

    Analyze the provided webpage content and extract detailed information about job opportunities.
    Determine whether this is:
    1. A specific job listing page with a single position, OR
    2. A generic job portal/listing page with multiple positions

    For a specific job listing, extract comprehensive details.
    For a generic portal, identify individual job listings that might be relevant for interim managers.

    Provide the information in a structured format with the following fields:
    - job_title: String (main job title or portal title)
    - company_name: String
    - location: String (if available)
    - job_type: String (if available)
    - description_summary: String summarizing the job or portal
    - responsibilities: List of strings (for specific job)
    - requirements: List of strings (for specific job)
    - keywords: List of strings with key terms from the job
    - url_found: String (URL where you found this job)
    - url_more_details: String (URL that points to more details about this job)
    - is_generic_portal: Boolean
    - specific_job_listings: List of dictionaries with {"title": "job title", "description": "short description", "url": "link"} for each job found on a portal page

  # Site Navigation Assistant prompt
  site_navigation: |
    You are an expert at analyzing website structure and navigation, especially for corporate career sites.
    You are given the HTML content of a webpage. Your task is to analyze it and determine:

    1. Whether this page contains job listings directly
    2. How to navigate to job listings if they're not on this page
    3. Whether the page has a search form for jobs
    4. The general structure of the site for navigation purposes

    IMPORTANT: Many German corporate sites use these terms for job listings:
    - "Stellenangebote" (Job Offers)
    - "Karriere" (Career)
    - "Offene Stellen" (Open Positions)
    - "Bewerbung" (Application)
    - "Aktuelle Vakanzen" (Current Vacancies)

    Focus on identifying:
    1. Links to job listing pages (may include words like "jobs", "careers", "positions")
    2. Search forms that can filter job listings
    3. Links to specific job postings
    4. Sections that might indicate this is already a job listing page

    For navigation paths, be specific about what links to click or search terms to use.

    Focus on identifying navigation elements that would lead to job listings, especially for senior or interim management positions.

    Provide your analysis in a structured format with the following fields:
    - has_job_listings: Boolean indicating if this page directly contains job listings
    - job_listings_path: String describing how to navigate to job listings (if not on this page)
    - search_form_path: String describing how to use the search functionality (if available)
    - navigation_pattern: String describing the typical navigation pattern of this site
    - site_structure: String describing the general structure of the site
    - recommendations: List of strings with recommendations for exploring this site

# Output configuration
output:
  # HTML report styling
  report_title: "Interim Manager Job Search Results"
  color_scheme:
    primary: "#2c3e50"
    secondary: "#3498db"
    success: "#27ae60"
    warning: "#f39c12"
    danger: "#e74c3c"
    background: "#f9f9f9"
    card_background: "#ffffff"

  # Report sections and content
  sections:
    - name: "Summary"
      include: true
      stats:
        - "Sites Visited"
        - "Job Details Explored"
        - "Relevant Jobs Found"
        - "Job Portals Identified"

    - name: "Relevant Job Positions"
      include: true

    - name: "Job Portals with Potential Opportunities"
      include: true

    - name: "Sites Visited"
      include: true

    - name: "Model Usage Summary"
      include: true
